<a href="https://colab.research.google.com/github/Shruti-2301/EDA/blob/main/EDA_Resampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data ={
    "Date": pd.date_range("2025-01-01", periods=10, freq='D'),
    "Sales": [100,129,150,130,160,180,200,170,190,220]
}
df=pd.DataFrame(data)
df.set_index("Date" , inplace=True)
print(df)

            Sales
Date
2025-01-01    100
2025-01-02    129
2025-01-03    150
2025-01-04    130
2025-01-05    160
2025-01-06    180
2025-01-07    200
2025-01-08    170
2025-01-09    190
2025-01-10    220

In [ ]:
monthly_sales=df["Sales"].resample("ME").sum()
print(monthly_sales)

Date
2025-01-31    1629
Freq: ME, Name: Sales, dtype: int64

In [ ]:
df["Sales"].resample("ME").mean() # average

Date
2025-01-31    162.9
Freq: ME, Name: Sales, dtype: float64

In [ ]:
df["Sales"].resample("ME").min() #Minimum

Date
2025-01-31    100
Freq: ME, Name: Sales, dtype: int64

In [ ]:
df["Sales"].resample("ME").max()

Date
2025-01-31    220
Freq: ME, Name: Sales, dtype: int64

In [ ]:
  .